name: nine_cb
version: 1.9.1
description: nine_cb
author: lolita_is_god
website: ~
softdepend: [WorldGuard, CoreProtect, essentials, icJukeBox]
#---
main: jp.hikahikaru17.dev.nine_cbs.nine_cbs
#---
commands:
    cbhelp:
        description: tell you help for CMD
        usage: '/<command>'
    cbwarp:
        description: warp to somewhere (FOR CB) (need essentials)
        usage: '/<command>'
    cbgm:
        description: change gamemode (FOR CB)
        usage: '/<command>'
    cbtp:
        description: teleport (FOR CB)
        usage: '/<command>'
    cbgive:
        description: give something (FOR CB)
        usage: '/<command>'
    cbtell:
        description: tell something (FOR CB)
        usage: '/<command>'
    cbsound:
        description: play sound (FOR CB)
        usage: '/<command>'
    cbtitle:
        description: show something (FOR CB)
        usage: '/<command>'
    cbsubtitle:
        description: show something (FOR CB)
        usage: '/<command>'
    cbeffect:
        description: some effect (FOR CB)
        usage: '/<command>'
    cbxp:
        description: give (or take) EXP (FOR CB)
        usage: '/<command>'
    cbspeed:
        description: change speed (FOR CB)
        usage: '/<command>'
    cbmenu:
        description: open menu (FOR CB) (need MyMenu)
        usage: '/<command>'
    cbgod:
        description: switch god effect (FOR CB)
        usage: '/<command>'
    cbtpt:
        description: switch anybody can teleport you (FOR CB)
        usage: '/<command>'
    cbfly:
        description: switch anybody can teleport you (FOR CB)
        usage: '/<command>'
    cbmusic:
        description: play music by player (FOR CB)
        usage: '/<command>'
    cbshot:
        description: give gun (FOR CB)
        usage: '/<command>'
    cbtell-a:
        description: tell players (default range is 10) something (FOR CB)
        usage: '/<command>'
    cbtitle-a:
        description: show players (default range is 10) something (FOR CB)
        usage: '/<command>'
    cbsubtitle-a:
        description: show players (default range is 10) something (FOR CB)
        usage: '/<command>'
    ninecb:
        description: admin only
        usage: '/<command>'
    cmd:
        description: none
        usage: '/<command>'
    cmb:
        description: place cb
        usage: '/<command>'
    uncmb:
        description: remove cb
        usage: '/<command>'
    umcmd:
        description: none
        usage: '/<command>'
    cbactionbar:
        description: action bar
        usage: '/<command>'
    cbactionbar-a:
        description: actionbar
        usage: '/<command>'
    cbback:
        description: back (need essentials)
        usage: '/<command>'
    back:
        description: a
        usage: '/<command>'

        
