name: nine_cb
version: 1.8.2
description: nine_cb
author: lolita_is_god
website: ~
depend: [WorldGuard, CoreProtect]
#---
main: jp.hikahikaru17.dev.nine_cbs.nine_cbs
#---
commands:
    cbhelp:
        description: tell you help for CMD
        usage: '/cbhelp'
    cbwarp:
        description: warp to somewhere (FOR CB)
        usage: '/cbwarp'
    cbgm:
        description: change gamemode (FOR CB)
        usage: '/cbgm'
    cbtp:
        description: teleport (FOR CB)
        usage: '/cbtp'
    cbgive:
        description: give something (FOR CB)
        usage: '/cbgive'
    cbtell:
        description: tell something (FOR CB)
        usage: '/cbtell'
    cbsound:
        description: play sound (FOR CB)
        usage: '/cbsound'
    cbtitle:
        description: show something (FOR CB)
        usage: '/cbtitle'
    cbsubtitle:
        description: show something (FOR CB)
        usage: '/cbsubtitle'
    cbeffect:
        description: some effect (FOR CB)
        usage: '/cbeffect'
    cbxp:
        description: give (or take) EXP (FOR CB)
        usage: '/cbxp'
    cbspeed:
        description: change speed (FOR CB)
        usage: '/cbspeed'
    cbmenu:
        description: open menu (FOR CB) (need MyMenu)
        usage: '/cbmenu'
    cbgod:
        description: switch god effect (FOR CB)
        usage: '/cbgod'
    cbtpt:
        description: switch anybody can teleport you (FOR CB)
        usage: '/cbtpt'
    cbmusic:
        description: play music by player (FOR CB)
        usage: '/cbmusic'
    cbshot:
        description: give gun (FOR CB)
        usage: '/cbshot'
    cbtell-a:
        description: tell players (default range is 10) something (FOR CB)
        usage: '/cbtell-a'
    cbtitle-a:
        description: show players (default range is 10) something (FOR CB)
        usage: '/cbtitle-a'
    cbsubtitle-a:
        description: show players (default range is 10) something (FOR CB)
        usage: '/cbsubtitle-a'
    ninecb:
        description: admin only
        usage: '/ninecb'
    cmd:
        description: none
        usage: '/cmd'
    cmb:
        description: place cb
        usage: '/cmb'
    uncmb:
        description: remove cb
        usage: '/uncmb'

        
